name: client
description: BookIT - frontend

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^1.1.0
  cupertino_icons: ^1.0.2
  carousel_slider: ^3.0.0
  http: any
  flutter_rating_bar: ^4.0.0
  google_nav_bar: ^5.0.5
  line_icons: ^2.0.1
  circular_profile_avatar: ^2.0.0
  percent_indicator: ^3.0.1
  expandable: ^5.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_name: "^0.0.1"
  flutter_launcher_icons: "^0.8.0"

flutter_launcher_name:
  name: "BookIT"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
        - asset: assets/fonts/Oswald-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/Oswald-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/Oswald-ExtraLight.ttf
          weight: 200

  assets:
    - assets/images/
    - assets/icons/
    - assets/localizable/

